Description: Cria um cluster Redshift que é publicamente acessível a partir da internet.
# Usando o jinja para monstar um template
Resources:

  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      AllowVersionUpgrade: true
      AutomatedSnapshotRetentionPeriod: 5
      AvailabilityZone: sa-east-1a
      ClusterIdentifier: redshift--cluster   # Sempre que abrir e fechar 2 chaves significa que é uma variável jinja
      ClusterParameterGroupName: !Ref RedshiftParameterGroup  # neste caso, está colocando uma variável de ambiente (producao, staging..)
      ClusterSubnetGroupName: !Ref RedshiftSubnetGroup        # e estou subindo com o mesmo script, sem precisar subir scripts diferentes.
      VpcSecurityGroupIds:
        - !Ref RedshiftEC2SecurityGroup
      ClusterType: multi-node
      DBName: app                    # Vai varrer o config.yaml até encontrar redshiftcluster->cluster e vai preencher com o conteúdo(app).
      Encrypted: true
      MasterUsername:      # Nao esta no arquivo, mas posso add como variável no github_actions.
      MasterUserPassword: 
      NodeType: dc2.large
      NumberOfNodes: 2
      PubliclyAccessible: true
      IamRoles:
        - !GetAtt RedshiftRole.Arn

  RedshiftSubnetGroup:
    Type: 'AWS::Redshift::ClusterSubnetGroup'
    Properties:
      Description: Redshift Subnet group
      SubnetIds:
        - !Ref RedshiftSubnet

  RedshiftParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Parameter group for redshift cluster
      ParameterGroupFamily: redshift-1.0
      Parameters:
        - ParameterName: max_concurrency_scaling_clusters
          ParameterValue: 0

             # Vai percorrer um for na lista de ambientes até encontrar o equivalente ao logado.
  
             # Vai percorrer um for na lista de ambientes até encontrar o equivalente ao logado.
  
  

  RedshiftEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redshift. Public access
      GroupName: redshift--security-group
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: 5439
          IpProtocol: tcp
          ToPort: 5439
      SecurityGroupIngress:
      
        - CidrIp: 5.6.7.8/32      # Lerá os ips do arquivo e novo for para preencher todos da lista aqui.
          FromPort: 5439
          IpProtocol: tcp
          ToPort: 5439
      
        - CidrIp: 1.2.3.4/32      # Lerá os ips do arquivo e novo for para preencher todos da lista aqui.
          FromPort: 5439
          IpProtocol: tcp
          ToPort: 5439
      
        - CidrIp: 9.10.11.12/32      # Lerá os ips do arquivo e novo for para preencher todos da lista aqui.
          FromPort: 5439
          IpProtocol: tcp
          ToPort: 5439
      
      VpcId: !Ref RedshiftVPC

  RedshiftEC2SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt RedshiftEC2SecurityGroup.GroupId
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !GetAtt RedshiftEC2SecurityGroup.GroupId

  RedshiftVPCInternetGateway:
    Type: AWS::EC2::InternetGateway

  RedshiftVPCAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref RedshiftVPC
      InternetGatewayId: !Ref RedshiftVPCInternetGateway

  RedshiftRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref RedshiftVPC

  RedshiftVPCRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref RedshiftVPCInternetGateway
      RouteTableId: !Ref RedshiftRouteTable

  RedshiftSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RedshiftRouteTable
      SubnetId: !Ref RedshiftSubnet

  RedshiftRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version : 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - redshift.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      RoleName: iam--redshift-role

  RedshiftSpectrumPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - arn:aws:s3:::*
          - Effect: Allow
            Action:
              - glue:CreateDatabase
              - glue:DeleteDatabase
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:UpdateDatabase
              - glue:CreateTable
              - glue:DeleteTable
              - glue:BatchDeleteTable
              - glue:UpdateTable
              - glue:GetTable
              - glue:GetTables
              - glue:BatchCreatePartition
              - glue:CreatePartition
              - glue:DeletePartition
              - glue:BatchDeletePartition
              - glue:UpdatePartition
              - glue:GetPartition
              - glue:GetPartitions
              - glue:BatchGetPartition
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - athena:*
            Resource:
              - "*"
      PolicyName: iam--redshift-spectrum-policy
      Roles:
        - !Ref RedshiftRole