Resources: 
  BeliscoRedshift:
    Type: AWS::Redshift::Cluster
    Properties: 
      AllowVersionUpgrade: true
      AutomatedSnapshotRetentionPeriod: 5
      AvailabilityZone: us-east-1a # Dentro da regiao north virginia tem 3 data-centers, estamos colocando na 1a apenas, sem redundancia
      ClusterIdentifier: my-redshift-cluster #Nome do cluster que vai aparecer no painel
      ClusterParameterGroupName: !Ref RedshiftParameterGroup #Referencia o carinha la embaixo: 
      ClusterSubnetGroupName: !Ref RedshiftSubnetGroup #vou no google e olho como cria
      VpcSecurityGroupIds: 
        - !Ref RedshiftEC2SecurityGroup
      ClusterType: multi-node
      DBName: production
      Encrypted: true
      MaterUserName: admin
      MaterUserPassword: Admin1234
      NodeType: dc2.large #define o tamanho em giga da minha cpu


RedshiftParameterGroup:  # Posso configurar para que ele aumente automaticamente o cluster quando uma aplicacao (pbix,por ex) estiver colocando o cluster no talo.
  Type: AWS::Redshift::ClusterParameterGroup
  Properties: 
    Description: String
    ParameterGroupFamily: redshift-1.0
    Parameters: 
      - ParameterName: max_concurrently_scaling_clusters
        ParameterValue: 1 
 
 
RedshiftSubnetGroup:  # criando a rede onde o redshift estará disponível
  Type: AWS::Redshift::ClusterParameterGroup
  Properties: 
    Description: String
    ParameterGroupFamily: redshift-1.0
    Parameters: 
      - ParameterName: max_concurrently_scaling_clusters
        ParameterValue: 1 

        #VPC é uma nuvem privada... somente recursos dentro da vpc poderao se ver 