name: Deploy CDK - S3 bucket

on:
  push:
    branches:
      - cdk_deploy_bb

jobs: 
  
  deploy:
    runs-on: ubuntu-latest          
    steps:
    - uses: actions/checkout@v2   
    - name: Set up Python           
      uses: actions/setup-python@v2 
      with: 
        python-version: '3.x'          
    - uses: actions/setup-node@v2-beta
      with: 
        node-version: '12'        
    - name: Install dependencies
      run: |                  
        sudo npm install -g aws-cdk   
        cd 2_continuous_integration_and_tests/CDK
        pip install -r requirements.txt   
    - name: Deploy    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}      
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: | 
        cd 2_continuous_integration_and_tests/CDK
        cdk synth
        cdk deploy